Microsoft Windows [Versión 10.0.18363.1256]
(c) 2019 Microsoft Corporation. Todos los derechos reservados.

C:\Users\RUIM10>cd C:\Users\RUIM10\Downloads\prueba


SQL*Plus: Release 11.1.0.7.0 - Production on Mar Mar 9 04:34:09 2021

Copyright (c) 1982, 2008, Oracle.  All rights reserved.


Conectado a:
Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 - 64bit Production
With the Partitioning, Automatic Storage Management, OLAP, Data Mining
and Real Application Testing options

SQL> @INSTALADOR_PRUEBA_CARCENTER.SQL

Tabla creada.


Comentario creado.


═ndice creado.


═ndice creado.


═ndice creado.


Tabla modificada.


Tabla modificada.


Tabla creada.


Tabla modificada.


Tabla modificada.


Tabla modificada.


Tabla creada.


Tabla modificada.


Tabla creada.


Comentario creado.


Tabla modificada.


Tabla creada.


Comentario creado.


Tabla modificada.


Tabla creada.


Comentario creado.


Tabla modificada.


Tabla creada.


═ndice creado.


Tabla modificada.


Tabla creada.


Comentario creado.


Tabla modificada.


Tabla creada.


Tabla modificada.


Tabla creada.


═ndice creado.


Tabla modificada.


Tabla modificada.


Tabla modificada.


Tabla creada.


Tabla modificada.


Tabla modificada.


Tabla creada.


Comentario creado.


Tabla modificada.


Tabla creada.


Comentario creado.


Tabla modificada.


Tabla creada.


Tabla modificada.


Tabla creada.


Tabla modificada.


Tabla modificada.


Tabla modificada.


Tabla modificada.


Tabla modificada.


Tabla modificada.


Tabla modificada.


Tabla modificada.


Tabla modificada.


Tabla modificada.


Tabla modificada.


Tabla modificada.


Tabla modificada.


Tabla modificada.


Tabla modificada.


Tabla modificada.


Tabla modificada.


Tabla modificada.


Tabla modificada.


Tabla modificada.

SQL> Desconectado de Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 - 64bit Production
With the Partitioning, Automatic Storage Management, OLAP, Data Mining
and Real Application Testing options

C:\Users\RUIM10\Downloads\prueba>